image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - docker info

stages:
  - build

build-image:
  stage: build
  script:
    - docker build -t todolist-ci .
